### ISSUE TITLE
Install error on macOS 

### ISSUE THREAD

**Issue by yaoyi2008** [Intsights/PyDomainExtractor#11]
> MacOS BigSur 11.2.3

> $ brew install gcc libidn2

is OK

but

> $ pip install pydomainextractor
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting pydomainextractor
  Using cached https://mirrors.aliyun.com/pypi/packages/70/81/1d4faabb5c7c14351ccc1e69f36f822e8d2958517ff95f3fe293bc1ed501/PyDomainExtractor-0.9.1.tar.gz (126 kB)
Using legacy 'setup.py install' for pydomainextractor, since package 'wheel' is not installed.
Installing collected packages: pydomainextractor
    Running setup.py install for pydomainextractor ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/xx/PycharmProjects/pythonProject/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b6/3p4psc6x6fnbv84226snn34c0000gn/T/pip-install-c3fcazi1/pydomainextractor_3e140deed58c463c9b158f3ab06ff95c/setup.py'"'"'; __file__='"'"'/private/var/folders/b6/3p4psc6x6fnbv84226snn34c0000gn/T/pip-install-c3fcazi1/pydomainextractor_3e140deed58c463c9b158f3ab06ff95c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/b6/3p4psc6x6fnbv84226snn34c0000gn/T/pip-record-j3la2jy6/install-record.txt --single-version-externally-managed --compile --install-headers /Users/xx/PycharmProjects/pythonProject/venv/include/site/python3.9/pydomainextractor
         cwd: /private/var/folders/b6/3p4psc6x6fnbv84226snn34c0000gn/T/pip-install-c3fcazi1/pydomainextractor_3e140deed58c463c9b158f3ab06ff95c/
    Complete output (27 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-11.2-x86_64-3.9
    creating build/lib.macosx-11.2-x86_64-3.9/tests
    copying tests/__init__.py -> build/lib.macosx-11.2-x86_64-3.9/tests
    copying tests/test_pydomainextractor.py -> build/lib.macosx-11.2-x86_64-3.9/tests
    creating build/lib.macosx-11.2-x86_64-3.9/pydomainextractor
    copying pydomainextractor/__init__.py -> build/lib.macosx-11.2-x86_64-3.9/pydomainextractor
    running egg_info
    writing PyDomainExtractor.egg-info/PKG-INFO
    writing dependency_links to PyDomainExtractor.egg-info/dependency_links.txt
    writing top-level names to PyDomainExtractor.egg-info/top_level.txt
    reading manifest file 'PyDomainExtractor.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'PyDomainExtractor.egg-info/SOURCES.txt'
    copying pydomainextractor/pydomainextractor.pyi -> build/lib.macosx-11.2-x86_64-3.9/pydomainextractor
    running build_ext
    building 'extractor' extension
    creating build/temp.macosx-11.2-x86_64-3.9
    creating build/temp.macosx-11.2-x86_64-3.9/src
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -Isrc -I/Users/xx/PycharmProjects/pythonProject/venv/include -I/Users/xx/.pyenv/versions/3.9.4/include/python3.9 -c src/extractor.cpp -o build/temp.macosx-11.2-x86_64-3.9/src/extractor.o -std=c++17
    clang++ -bundle -undefined dynamic_lookup -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/xx/.pyenv/versions/3.9.4/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/xx/.pyenv/versions/3.9.4/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib build/temp.macosx-11.2-x86_64-3.9/src/extractor.o -o build/lib.macosx-11.2-x86_64-3.9/pydomainextractor/extractor.cpython-39-darwin.so -lidn2 -Wl,--strip-all
    ld: unknown option: --strip-all
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command '/usr/bin/clang++' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/xx/PycharmProjects/pythonProject/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b6/3p4psc6x6fnbv84226snn34c0000gn/T/pip-install-c3fcazi1/pydomainextractor_3e140deed58c463c9b158f3ab06ff95c/setup.py'"'"'; __file__='"'"'/private/var/folders/b6/3p4psc6x6fnbv84226snn34c0000gn/T/pip-install-c3fcazi1/pydomainextractor_3e140deed58c463c9b158f3ab06ff95c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/b6/3p4psc6x6fnbv84226snn34c0000gn/T/pip-record-j3la2jy6/install-record.txt --single-version-externally-managed --compile --install-headers /Users/xx/PycharmProjects/pythonProject/venv/include/site/python3.9/pydomainextractor Check the logs for full command output.

**Comment by wavenator** [comment]
It looks like there is a problem with your linker. It does not know the flag "--strip-all" which is weird.
I will search for a solution. In the meantime, can you please upload the output of the following command:
```shell
ld --help
```
Thanks!

**Comment by wavenator** [comment]
The library now ships binary packages that also target MacOS. If the issue still persists, I'd be happy to know that. In the meantime, I close this issue.
