### ISSUE TITLE
Support Apple Silicon

### ISSUE THREAD

**Issue by dhkron** [Intsights/PyDomainExtractor#13]
It appears that even though version 0.11.0 is rust-based, a wheel for apple silicon isn't available - installing with pip throws an error.
Can you add M1 to the release?

```
Skipping link: none of the wheel’s tags (cp39-cp39-macosx_10_7_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/37/c1/ba1152e8b7457d66b035debe0c996c5a597aa1a9e438997dbd31b9e6c08d/pydomainextractor-0.11.0-cp39-cp39-macosx_10_7_x86_64.whl#sha256=0d0fd67f80b1772e279b00c1374639c882f583b7aa58bf81f54fbaaa92aaedf4 (from https://pypi.org/simple/pydomainextractor/) (requires-python:>=3.7)
```

**Comment by wavenator** [comment]
It is now supported via a new source distribution. Github actions does not have an M1 runner which makes it very hard to distribute a binary wheel for Apple M1. We will look for a solution in the future.
