### ISSUE TITLE
Library crashes python on some invalid inputs

### ISSUE THREAD

**Issue by dhkron** [Intsights/PyDomainExtractor#4]
Hey,

I've noticed that for some inputs, the method `is_valid_domain` crashes python altogether.
To reproduce -
```python
import pydomainextractor

domain_extractor = pydomainextractor.DomainExtractor()
domain_extractor.is_valid_domain('www.google.com.')```
```
Thanks!

**Comment by wavenator** [comment]
Good catch!
I didn't adapt `is_valid_domain` to handle `extract` new exceptions on invalid inputs.

Fixed on version 0.6.1
Thanks!
