### ISSUE TITLE
tld-suffix 教育.hk is not recognized

### ISSUE THREAD

**Issue by nitzspiz** [Intsights/PyDomainExtractor#7]
How to reproduce:
call ```extract_from_url``` with u'http://xn--zckzap6140b352by.blog.so-net.教育.hk'  as input
extract_from_url will raise Invalid Domain Error.
expected behavior is to return ```{subdomain: xn--zckzap6140b352by.blog, domain: so-net, suffix: 教育.hk}```

**Comment by wavenator** [comment]
I could not reproduce it. Can you ensure you are testing it with the latest version?

**Comment by nitzspiz** [comment]
you are right, I was using a dirty build of the program.
I'm closing this. but notice there are cases that still reproduce
